[package]
name = "obstinate"
version = "0.1.0"
edition = "2021"
description = "Experimental memory mapped like interface on top of object_store."
license = "Apache-2.0"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
